#! /bin/bash

bat=$(cat /sys/class/power_supply/BAT0/capacity)

if [ $bat -ge 80 ]; then
    bat_color="#00FF00";
elif [ $bat -ge 60 ]; then
    bat_color="#80FF00";
elif [ $bat -ge 40 ]; then
    bat_color="#FFFF00";
elif [ $bat -ge 20 ]; then
    bat_color="#FF8000";
else
    bat_color="#FF0000";
fi

echo $bat_color
