#!/bin/bash

network=$(iw wlp1s0 info | grep ssid | cut -d' ' -f 2-)
ip=$(ip -4 -o addr show wlp1s0 | sed 's/^.*inet //' | sed 's:/.*$::')

if [ -z "$network" ]; then
    echo "No network"
else
    echo $ip
fi
